### ISSUE TITLE
Extreme lag when used in conjunction with Sounds and Sound Physics Remastered

### ISSUE THREAD

**Issue by Fyoncle** [Tschipcraft/fabric_make_bubbles_pop_mod#16] opened 2024-07-16 13:58 UTC
### Describe the bug

https://github.com/IMB11/Sounds/issues/68#
https://github.com/IMB11/Sounds/issues/77
Read these two issues.

### Steps to reproduce

Stated in the previous issues.

### Expected behavior

To not lag.

**Comment by Tschipcraft** [comment] 2024-07-16 15:03
Thank you for the bug report. Make Bubbles Pop produces a lot of bubble_pop sound events when bubble particles pop, so this might be the underlying issue here, as the sound physics mod obviously has to do quite a lot more work for them than vanilla.
Turning down the bubble pop volume in the config (added in v0.3.0) might solve this issue. I say might, because atm the sound events are still created with volume set to 0.

I'm not sure what role the Sounds mod plays in this though... Could be that it changes the sound system in some way that makes it performs worse on some systems?

**Comment by Fyoncle** [comment] 2024-07-16 15:13
I tried to close specific things in config already, but didnt help. If you want more information Sounds mod 0.9.0 doesn't cause this issue, after it updated to 1.0.1 or something it started happening.

**Comment by Fyoncle** [comment] 2024-07-16 15:50
Also reported this to the Sound Physics Remastered, which is he said its your mod's problem https://github.com/henkelmax/sound-physics-remastered/issues/232

**Comment by Tschipcraft** [comment] 2024-07-16 16:18
Interesting, I'll take a look at this

**Comment by Tschipcraft** [comment] 2024-07-16 16:45
I did the cow test mentioned in the linked issues in Fabric 1.20.1:

**Test 1:**
- Sounds **0.9.0**
- Make Bubbles Pop v0.3.0
- Sound Physics 1.4.5

No issues, fps is stable

**Test 2:**
- Sounds 1.1.0
- Make Bubbles Pop v0.3.0
- Sound Physics 1.4.5

Fps is horrible, problem disappears when bubble pop volume is set to 0

**Test 3:**
- Sounds 1.1.0
- Make Bubbles Pop **v0.2.0**
- Sound Physics 1.4.5

Same as test 2

So, I'm guessing the underlying issue is caused by the Sounds mod

**Comment by Fyoncle** [comment] 2024-07-16 16:46
> I did the cow test mentioned in the linked issues in Fabric 1.20.1: ... (Edit: trimmed quote)

He said theres no mixin conflicts or anything with your mod, and refused to fix it so i am still not sure.

**Comment by Tschipcraft** [comment] 2024-07-16 16:56
I found that I can reproduce the low fps when chaining four command blocks together, each with the command
```mcfunction
playsound minecraft:block.stone.break ambient @a
```
Sound Physics 1.4.5 and Sounds **1.1.0**:
![2024-07-16_18 51 10](https://github.com/user-attachments/assets/570f8844-777b-4c9a-b83a-bd1e5be95480)

Sound Physics 1.4.5 and Sounds **0.9.0**:
![2024-07-16_18 49 52](https://github.com/user-attachments/assets/ce5a36b7-3ee3-4ac4-aca7-7502d9671f33)

I'll post this over on the Sounds issue

**Comment by Fyoncle** [comment] 2024-07-16 16:56
> I found that I can reproduce the low fps when chaining four command blocks together, each with the command
> 
> ```mcfunction
> playsound minecraft:block.stone.break ambient @a
> ```
> 
> Sounds **1.1.0**: ![2024-07-16_18 51 10](https://private-user-images.githubusercontent.com/78470530/349204945-570f8844-777b-4c9a-b83a-bd1e5be95480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDkyNzEsIm5iZiI6MTcyMTE0ODk3MSwicGF0aCI6Ii83ODQ3MDUzMC8zNDkyMDQ5NDUtNTcwZjg4NDQtNzc3Yi00YzlhLWI4M2EtYmQxZTViZTk1NDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE2NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViM2ZiNWQ2NWEwYjIxNDFmNDdkOTVlMWQ1OTdlYTAwYzhhMmFmODRmYmUzMjIwMjc2YjllOTFjNGY1NmI2YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3p5P-9ceYW5tELhcYTKX85bniAYmkzOAt3LolmppWpQ)
> 
> Sounds **0.9.0**: ![2024-07-16_18 49 52](https://private-user-images.githubusercontent.com/78470530/349205067-ce5a36b7-3ee3-4ac4-aca7-7502d9671f33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDkyNzEsIm5iZiI6MTcyMTE0ODk3MSwicGF0aCI6Ii83ODQ3MDUzMC8zNDkyMDUwNjctY2U1YTM2YjctM2VlMy00YWM0LWFjYTctNzUwMmQ5NjcxZjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE2NTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDJiZTJhN2M4NGRmNDk1YTIxMDUwNjYzMDdiNWE0MWYyYzg1NDRkYTRiZjVlMGQ2MzViZmE2MDJiZTQzYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WrJ2P6GDncAdg2fjLkgj0LZ3QjzQA2BhxIpcMFpWc_A)
> 
> I'll post this over on the Sounds issue

Thank you for your insanely detailed tests that i cannot even imagine lmao, i hope IMB11 can reproduce these issues and fix it.

**Comment by Fyoncle** [comment] 2024-07-28 13:49
![image](https://github.com/user-attachments/assets/62f5d8e7-e873-49d9-8bee-a03ea4cd0343)
Uh so, do you have any idea to fix that

**Comment by Fyoncle** [comment] 2024-07-31 19:08
@Tschipcraft i forgot to tag :v

**Comment by Tschipcraft** [comment] 2024-08-03 17:47
I added a comment there

<details>
<summary>For anyone too lazy to look at the other issue</summary>

Make Bubbles Pop increases the bubble particle lifetime a bit compared to vanilla to allow the bubbles to reach the water surface more often. Since Guardians produce a lot of bubbles when they swim around, the particle count increases quite quickly, causing low fps. I might be able to reduce the particle count they produce in a future update. For now, bubble lifetime can also be decreased in the settings (related to https://github.com/Tschipcraft/make_bubbles_pop/issues/4#issuecomment-1758593635)

</details>

**Comment by Fyoncle** [comment] 2024-08-28 15:18
@Tschipcraft I removed sounds, and your mod is the reason of the guardian beam lag, so Sounds is not related to this issue.

**Comment by Tschipcraft** [comment] 2024-08-28 15:26
Well yes, that's what I wrote in my comment

**Comment by Fyoncle** [comment] 2024-08-28 15:27
> Well yes, that's what I wrote in my comment

Wait no, none of these 3 mods is the reason, i also get that issue with all of that 3 combo disabled, theres something wrong... theres a 4th incompatibility...

**Comment by Tschipcraft** [comment] 2024-08-28 15:56
So it happens without Make Bubbles Pop is what you're saying?

**Comment by Fyoncle** [comment] 2024-08-28 15:57
> So it happens without Make Bubbles Pop is what you're saying?

Without sounds, without make bubbles pop, without sound physics remastered.

**Comment by Fyoncle** [comment] 2024-08-28 16:13
> So it happens without Make Bubbles Pop is what you're saying?

Now it doesn't happen, i think problem is at the "ocean monument" instead of the beams itself.

**Comment by Fyoncle** [comment] 2024-08-28 16:42
Nvm this doesn't happen places with no water, but if you also place water on somewhere else it also doesn't happen, but if you try it on a ocean biome, it happens, on monuments too, thats too interestingn and idk what triggers that.

**Comment by Fyoncle** [comment] 2024-08-28 18:51
Mod called https://modrinth.com/mod/lambdynamiclights is the cause of everything.

**Comment by Fyoncle** [comment] 2024-08-28 18:53
Theres 5th incompatibility too...

**Comment by Tschipcraft** [comment] 2024-08-28 19:04
> Mod called [modrinth.com/mod/lambdynamiclights](https://modrinth.com/mod/lambdynamiclights) is the cause of everything.

I have a [dynamic lights](https://github.com/Tschipcraft/dynamiclights) mod as well  
<img height="48px" src="https://cdn.discordapp.com/emojis/1040722834122604594.webp?size=128&quality=lossless&name=idk">

**Comment by Tschipcraft** [comment] 2024-08-28 19:05
Anyway, since this has nothing to do with Make Bubbles Pop anymore, I think we can close this, right?

**Comment by Fyoncle** [comment] 2024-08-28 19:07
> Anyway, since this has nothing to do with Make Bubbles Pop anymore, I think we can close this, right?

Ill make one more test after finding the 5th mod, i am currently so close to finding it with Binary Searching, ill talk to you back in 30 mins if that's fine?

**Comment by Fyoncle** [comment] 2024-08-28 19:28
Both of my folders does not give any result, but when mixed they do.

So theres 6th incompatibility. Searching!

**Comment by Fyoncle** [comment] 2024-08-28 20:05
Theres tens of combinations, almost impossible to find 2 conflicting mods
Have any idea?

**Comment by Tschipcraft** [comment] 2024-08-29 14:12
Nope

**Comment by Fyoncle** [comment] 2024-08-29 16:55
> > Mod called [modrinth.com/mod/lambdynamiclights](https://modrinth.com/mod/lambdynamiclights) is the cause of everything.
> 
> I have a [dynamic lights](https://github.com/Tschipcraft/dynamiclights) mod as well <img alt="" height="48px" src="https://camo.githubusercontent.com/4a198eea203da400a2ba624d3461f8a1b064089328d23016d6bd3d4542702854/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f313034303732323833343132323630343539342e776562703f73697a653d313238267175616c6974793d6c6f73736c657373266e616d653d69646b">

Your mod is causing the same chaos.
![image](https://github.com/user-attachments/assets/265b4d3f-766f-4f3e-8b84-9a9d47934c21)
FPS Falling to around 4 or 6 when guardians hit beams. When all the dynamic light mods disabled, everythings fine.

**Comment by Tschipcraft** [comment] 2024-08-31 15:18
My dynamic lights mod doesn't touch guardians or their beam at all, so I really don't think that's the issue there. Anyhow, this has nothing to do with Make Bubble Pop anymore. I will close this issue as resolved. If you want me to fix the dynamic lights issue, head over to the other repo and create a new bug report, including what other mods you are using so that I can actually debug this

**Closed as completed by Tschipcraft** 2024-08-31 15:18 UTC
Labels: bug, resolution: external
