### ISSUE TITLE
update to 1.20.6

### ISSUE THREAD

**Issue by screechystrings** [Tschipcraft/fabric_make_bubbles_pop_mod#14] opened 2024-05-25 22:04 UTC
### Describe the feature you'd like

just an update to 1.20.6 because this mod is cool

**Comment by Tschipcraft** [comment] 2024-06-21 14:29
I will finalize v0.3.0 with 1.20.6 support in approx. 2 weeks after my finals. Thanks for your patience!

**Comment by Tschipcraft** [comment] 2024-06-21 14:30
Duplicate of #13

**Closed as completed** 2024-07-14 18:52 UTC
Labels: resolution: duplicate, enhancement
